export const AGREGANDO_CLIENTE = 'AGREGANDO_CLIENTE';
export const CLIENTE_AGREGADO_EXITO = 'CLIENTE_AGREGADO_EXITO';
export const AGREGAR_CLIENTE_ERROR = 'AGREGAR_CLIENTE_ERROR';

export const COMENZAR_DESCARGA_CLIENTES = 'COMENZAR_DESCARGA_CLIENTES';
export const DESCARGA_CLIENTES_EXITO = 'DESCARGA_CLIENTES_EXITO';
export const DESCARGA_CLIENTES_ERROR = 'DESCARGA_CLIENTES_ERROR';

export const OBTENER_CLIENTE_MOSTRAR = 'OBTENER_CLIENTE_MOSTRAR';
export const CLIENTE_MOSTRAR_EXITO = 'CLIENTE_MOSTRAR_EXITO';
export const CLIENTE_MOSTRAR_ERROR = 'CLIENTE_MOSTRAR_ERROR';

export const OBTENER_CLIENTE_ELIMINAR = 'OBTENER_CLIENTE_ELIMINAR';
export const CLIENTE_ELIMINADO_EXITO = 'CLIENTE_ELIMINADO_EXITO';
export const CLIENTE_ELIMINADO_ERROR = 'CLIENTE_ELIMINADO_ERROR';

export const CARGAR_CLIENTE_EDITAR = 'CARGAR_CLIENTE_EDITAR';
export const OBTENER_CLIENTE_EDITAR = 'OBTENER_CLIENTE_EDITAR';
export const OBTENER_CLIENTE_ERROR = 'OBTENER_CLIENTE_ERROR';

export const COMENZAR_EDICION_CLIENTE = 'COMENZAR_EDICION_CLIENTE';
export const CLIENTE_EDITADO_EXITO = 'CLIENTE_EDITADO_EXITO';
export const CLIENTE_EDITADO_ERROR = 'CLIENTE_EDITADO_ERROR';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
